"""
算子工厂统一导出入口（WorldQuant BRAIN 风格）。

按类别分模块实现；此处 ``__all__`` 汇总，便于 ``from api.operators import rank, ts_mean``。
"""

from __future__ import annotations

from api.operators.cleaning import (
    pasteurize,
    protected_div,
    protected_log,
    protected_sqrt,
    tail,
)
from api.operators.context import change_instrument, orthogonalize
from api.operators.arithmetic import (
    abs_,
    add,
    cos_,
    densify,
    divide,
    inverse,
    log,
    max_,
    min_,
    multiply,
    power,
    reverse,
    signed_power,
    sign,
    sin_,
    sqrt,
    subtract,
)
from api.operators import future_data as _future_data
from expr.alternative import ALTERNATIVE_STUB_OPS
from expr.fundamental import FUNDAMENTAL_STUB_OPS
from expr.microstructure import MICROSTRUCTURE_STUB_OPS

_FUTURE_STUB_NAMES = sorted(
    FUNDAMENTAL_STUB_OPS | ALTERNATIVE_STUB_OPS | MICROSTRUCTURE_STUB_OPS
)
for _name in _FUTURE_STUB_NAMES:
    globals()[_name] = getattr(_future_data, _name)
del _future_data, _name
from api.operators.cs import (
    neutralize,
    normalize,
    quantile,
    rank,
    scale,
    winsorize,
    zscore,
)
from api.operators.group import (
    group_backfill,
    group_mean,
    group_neutralize,
    group_rank,
    group_scale,
    group_zscore,
)
from api.operators.logical import (
    and_,
    eq,
    ge,
    gt,
    if_else,
    is_nan,
    le,
    lt,
    ne,
    not_,
    or_,
)
from api.operators.transformational import bucket, trade_when
from api.operators.technical import (
    ts_ad,
    ts_adosc,
    ts_adx,
    ts_adxr,
    ts_apo,
    ts_aroon,
    ts_atr,
    ts_bbands,
    ts_bop,
    ts_cci,
    ts_cmo,
    ts_dema,
    ts_donchian,
    ts_dx,
    ts_ema,
    ts_kama,
    ts_keltner,
    ts_linearreg_angle,
    ts_linearreg_slope,
    ts_ma_envelope,
    ts_macd,
    ts_mfi,
    ts_mom,
    ts_natr,
    ts_obv,
    ts_ppo,
    ts_roc,
    ts_rocr100,
    ts_rocr,
    ts_rsi,
    ts_sar,
    ts_sma,
    ts_stochf,
    ts_stoch,
    ts_stochrsi,
    ts_t3,
    ts_tema,
    ts_trange,
    ts_trima,
    ts_trix,
    ts_ultosc,
    ts_willr,
    ts_wma,
)
from api.operators.ts import (
    delay,
    days_from_last_change,
    hump,
    kth_element,
    last_diff_value,
    ts_arg_max,
    ts_arg_min,
    ts_av_diff,
    ts_backfill,
    ts_corr,
    ts_count_nans,
    ts_covariance,
    ts_decay_linear,
    ts_delay,
    ts_delta,
    ts_kurt,
    ts_max,
    ts_mean,
    ts_min,
    ts_product,
    ts_quantile,
    ts_rank,
    ts_regression,
    ts_scale,
    ts_skew,
    ts_std,
    ts_std_dev,
    ts_step,
    ts_sum,
    ts_zscore,
)
from api.operators.vector import vec_avg, vec_sum

__all__ = [
    "abs_",
    "add",
    "and_",
    "bucket",
    "change_instrument",
    "cos_",
    "delay",
    "days_from_last_change",
    "densify",
    "divide",
    "eq",
    "ge",
    "group_backfill",
    "group_mean",
    "group_neutralize",
    "group_rank",
    "group_scale",
    "group_zscore",
    "gt",
    "hump",
    "if_else",
    "inverse",
    "is_nan",
    "kth_element",
    "last_diff_value",
    "le",
    "log",
    "lt",
    "max_",
    "min_",
    "multiply",
    "ne",
    "neutralize",
    "normalize",
    "not_",
    "orthogonalize",
    "or_",
    "pasteurize",
    "power",
    "protected_div",
    "protected_log",
    "protected_sqrt",
    "quantile",
    "rank",
    "reverse",
    "scale",
    "signed_power",
    "sign",
    "sin_",
    "sqrt",
    "subtract",
    "tail",
    "trade_when",
    "ts_ad",
    "ts_adosc",
    "ts_adx",
    "ts_adxr",
    "ts_apo",
    "ts_aroon",
    "ts_atr",
    "ts_bbands",
    "ts_bop",
    "ts_cci",
    "ts_cmo",
    "ts_dema",
    "ts_donchian",
    "ts_dx",
    "ts_ema",
    "ts_kama",
    "ts_keltner",
    "ts_linearreg_angle",
    "ts_linearreg_slope",
    "ts_ma_envelope",
    "ts_macd",
    "ts_mfi",
    "ts_mom",
    "ts_natr",
    "ts_obv",
    "ts_ppo",
    "ts_roc",
    "ts_rocr100",
    "ts_rocr",
    "ts_rsi",
    "ts_sar",
    "ts_sma",
    "ts_stochf",
    "ts_stoch",
    "ts_stochrsi",
    "ts_t3",
    "ts_tema",
    "ts_trange",
    "ts_trima",
    "ts_trix",
    "ts_ultosc",
    "ts_willr",
    "ts_wma",
    "ts_arg_max",
    "ts_arg_min",
    "ts_av_diff",
    "ts_backfill",
    "ts_corr",
    "ts_count_nans",
    "ts_covariance",
    "ts_decay_linear",
    "ts_delay",
    "ts_delta",
    "ts_kurt",
    "ts_max",
    "ts_mean",
    "ts_min",
    "ts_product",
    "ts_quantile",
    "ts_rank",
    "ts_regression",
    "ts_scale",
    "ts_skew",
    "ts_std",
    "ts_std_dev",
    "ts_step",
    "ts_sum",
    "ts_zscore",
    "vec_avg",
    "vec_sum",
    "winsorize",
    "zscore",
]
__all__.extend(_FUTURE_STUB_NAMES)
del _FUTURE_STUB_NAMES
